apiVersion: v1
kind: Service
metadata:
  name: architect-go
  labels:
    app: architect-go
  annotations:
    description: "architect-go API Service"
spec:
  type: ClusterIP
  selector:
    app: architect-go
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
