apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: architect-go
  namespace: architect-production
  labels:
    app: architect-go
    environment: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: architect-go
subjects:
- kind: ServiceAccount
  name: architect-go
  namespace: architect-production
